# Generated by Django 3.2 on 2021-05-02 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210502_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 18, 54, 18, 901214, tzinfo=utc)),
        ),
    ]
